[[docs]]
  name = "Mode d'emploi"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[main]]
  name = "Docs"
  url = "/docs/prologue/introduction/"
  weight = 10

[[main]]
  name = "E2"
  url = "https://e2.spinster.party/"
  weight = 20

[[main]]
  name = "T"
  url = "https://t.spinster.party/"
  weight = 30

[[main]]
  name = "WTF"
  url = "https://wtf.spinster.party/"
  weight = 40
